import { Albert_Sans } from 'next/font/google';
import './globals.css';
import ProviderSession from '@/components/Providers';

const albertSans = Albert_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`bg-[#FAF9F4] ${albertSans.className}`}>
        <ProviderSession>{children}</ProviderSession>
      </body>
    </html>
  );
}
